version: '3.8'

services:
  # USUARIO PARA CONECTAR ES: SA
  sqlserver_apuntesnet:
    container_name: sqlserver_apuntesnet
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Apuntes@Net!
      ACCEPT_EULA: Y
