version: '3.8'

services:
  mysql_apuntesnet:
    container_name: mysql_apuntesnet
    image: mysql:latest
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: 'AdoNetMySqlDatabase'
      MYSQL_ROOT_PASSWORD: '123456'