version: '3.8'

services:
  mysql_apuntesnet:
    container_name: mysql_benchmarks
    image: mysql:latest
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_DATABASE: 'BenchmarkingDatabases'
      MYSQL_ROOT_PASSWORD: '123456'
    volumes: 
      - .docker/InitMySql.sql:/docker-entrypoint-initdb.d/init.sql:rw