version: '3.8'

services:
  mysql_apuntesnet:
    container_name: mysql_apuntesnet
    image: mysql:latest
    restart: always
    ports: 
      - 3306:3306
    environment: 
      MYSQL_ROOT_PASSWORD: '123456'
    command: --init-file /data/application/initMysql.sql
    volumes: 
      - .docker/bbdd/initMysql.sql:/data/application/initMysql.sql

  # USUARIO PARA CONECTAR ES: SA
  sqlserver_apuntesnet:
    container_name: sqlserver_apuntesnet
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: always
    ports:
      - 1433:1433
    environment:
      SA_PASSWORD: Apuntes@Net!
      ACCEPT_EULA: Y