version: '3.8'

services:
  redis_cachear:
    image: 'bitnami/redis:latest'
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=password123
    volumes:
      - redis_data:/data
volumes:
  redis_data: