/* NOMBRE, APELLIDO1 Y TELEFONO DE LOS JEFES DE DPTO */

SELECT E.NOM, E.APEL1, E.TELEFONO

FROM DPTOS D, EMPLEADOS E --CUANDO EN FROM HAY MAS DE UNA TABLA EL SISTEMA HACE EL PRODUCTO CARTESIANO(REALIZA TODAS LAS CONBINACIONES POSIBLES ENTRE DICHAS TABLAS)

WHERE D.DNI_JEFE = E.DNIs

/* cada empleado obtinen sunombre y el nombre de su jefe inmediato */

SELECT  E1.NOMBRE "NOMBRE DEL EMPLEADO", E2.NOMBRE"NOMBRE DEL JEFE"

FROM EMPLEADOS E1, EMPLEADOS E2

WHERE e1.dni_j = E2.DNI

/*

DNI 	NOMBRE 		DNI_JEFE	DNI 	NOMBRE 		DNI_JEFE
1		A 				4		1			A 			4
1		A 				4		2 			B 			4
1		A 				4 		3			C 			2
1		A 				4 		4 			D 			4
2		B 				4		1			A 			4
...(CONBINA TODOS LOS DE LA TABLA EM1 CON LOS DE E2) 

*/

-- DNI DE LOS EMPLEADOS A SU CARGO

SELECT DISTINCT DNI_EMPL 

FROM FAMILIARES

--_________________________________________________--

SELECT DISTINCT F.DNI_EMPL

FROM EMPLE E, FAMIL F

WHERE E.DNI = F.DNI_EMPL

/* AUMENTAR TODOS LOS PRESUPUESTOS DE EN UN 10% Y OBTENER LA DESCRIPCION DEL PRESUPUESTO OBTENIDO */

SELECT DESCRIPCION, PRESUPUESTO( PRESUPUESTO * 1,1 ) "PRESUPUESTO TOTAL"

FROM PROYECTO

WHERE P.COD_DPTO = D.COD_DPTO AND DNOM = "COMPRAS"