SELECT E.NOMBRE, E.APELL1, E.APELL2, D.NOMB_DPTO, Z.DESCRIP

FROM EMPLEADOS E, DEPARTAMENTOS D, ZONA Z

WHERE E.COD_ZONA = Z.COD_ZONA AND E.COD_DPTO = D.COD_DPTO
	
	AND E.DNI NOT IN (	SELECT DISTINCT DNI_EMPL
						FROM FAMILIAR F
					 )

SELECT *

FROM EMPL

WHERE SALARIO > ANY (	SELECT DISTINCT SALARIO
						
						FROM EMPL

						WHERE PROVINCIA = "BIZKAIA")


--_________________________________________________________________________________________________________--

/* Sentencia Join

nombre de los empleados y nombre de los departamentos donde trabajan

SELECT E.NOM_EMPL, D.NOM_DPTO

FROM EMPL , DPTOS D

WHERE E.COD_DPTO = D.COD_DPTO


-----------------------------------------

ES LO MISMO QUE LO DE ARRIBA:

SELECT E.NOM_EMPL, D.NOM_DPTO

FROM EMPL E NATURAL JOIN DPTOS D

-------------------------------------------------------

ES LO MISMO QUE LOS OTROS DOS:

SELECT E.NOM_EMPL, D.NOM_DPTO

FROM EMPL E JOIN DPTOS D ON E.COD_DPTO = D.COD_DPTO

 */

 --NOMBRE DE LOS EMPLEADOS Y NOMBRE DEL DPTO DONDE TRABAJAN, EN EL CASO DE QUE UN EMPLEADO NO TENGA INFORMACION EN LA COLUMNACOD_DPTO APARECERA SOLAMENTE SU NOMBRE

 SELECT

 FROM EMPL E, DPTO D

 WHERE COD_DPTO IS NOT NULL AND E.COD_DPTO = D.COD_DPTO

 --LEFT JOIN COJE TODOS LOS REGISTROS DE LA TABLA COLOCADA EN FROM EN LA IZQUIERDA Y LAS COMBINA CON LA TABLA DE LA DERECHA, SINO ENCUENTRA CORRESPONDENCIA DEJA LOS CAMPOS EN BLANCO
 --RIGHT JOIN LO MISMO QUE LEFT JOIN PERO AL CONTRARIO... 

 SELECT E.NOMBRE, D.NOMBRE

 FROM EMPL E LEFT JOIN DPTOS D ON E.COD_DPTO = D.COD_DPTO

 --NOMBRE DE TODOS LOS EMPLEADOS DE LA TABLA DE EMPLEADOS, JUNTO CON EL NOMBRE DEL PROYECTO EN LOS QUE HA TRABAJADO MAS DE 10H Y SINO SE CUMPLE ESTA CONDICION SOLO APARECERA EL NOMBRE
 --DEL EMPLEADO

 SELECT E.NOM, P.NOM_PROY

 FROM (EMPL E, LEFT JOIN TRABAJA T ON E.DNI = T.DNI) (JOIN PROYECTOS P ON T.COD_PROY = P.COD_PROY)

 WHERE HORAS > 10

 --DE LOS EMPLEADOS DELDEPARTAMENTO DE FINANZAS OBTENER NOMBRE Y NOMBRE DEL JEFE INMEDIATO

 