// <auto-generated />
using System;
using Apuntes.Back.Core.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace UpdateDatabaseMigrations.Migrations.ContextoMSSQLMigrations
{
    [DbContext(typeof(ContextoMSSQL))]
    partial class ContextoMSSQLModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Apuntes.Back.Core.SQLite.ModelosBBDD.ModeloDosConClaveForanea", b =>
                {
                    b.Property<int>("IDMaterial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ID")
                        .HasColumnType("int");

                    b.Property<string>("Material")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TipoMaterial")
                        .HasColumnType("int");

                    b.HasKey("IDMaterial");

                    b.HasIndex("ID");

                    b.ToTable("Material");
                });

            modelBuilder.Entity("Apuntes.Back.Core.SQLite.ModelosBBDD.ModelosParaBBDD", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Apellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Apuntes.Back.Core.SQLite.ModelosBBDD.ModeloDosConClaveForanea", b =>
                {
                    b.HasOne("Apuntes.Back.Core.SQLite.ModelosBBDD.ModelosParaBBDD", "UsuarioID")
                        .WithMany("Material")
                        .HasForeignKey("ID");
                });
#pragma warning restore 612, 618
        }
    }
}
