// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlServerEfCore.Database;

#nullable disable

namespace MigrationsSqlServer.Migrations
{
    [DbContext(typeof(EntityFrameworkSqlServerContext))]
    [Migration("20241231153529_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlServerEfCore.Database.Entities.Pueblo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Pueblos");
                });

            modelBuilder.Entity("SqlServerEfCore.Database.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaHoy")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PuebloId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PuebloId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("SqlServerEfCore.Database.Entities.Usuario", b =>
                {
                    b.HasOne("SqlServerEfCore.Database.Entities.Pueblo", "PuebloIdNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("PuebloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PuebloIdNavigation");
                });

            modelBuilder.Entity("SqlServerEfCore.Database.Entities.Pueblo", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
