[package]
name = "rustCallback"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "callback"
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
async-std = "*"
