version: '3.8'

services:
  mongodb_apuntesnode:
    container_name: mongodb_apuntesnode
    image: mongo
    restart: always
    ports:
      - 27017-27019:27017-27019
    volumes:
      - .docker/bbdd/initMongoDB.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
